plugin: aws_ec2
regions:
  - us-east-1   # adjust to your AWS region
filters:
  tag:SDLC_ENVIRONMENT: prod
hostnames:
  - public-ip-address
compose:
  ansible_host: public_ip_address
groups:
  dev: "'MyAppServer' in tags.Name"
